# Copyright (c) Cratis. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

defmodule Chronicle.Artifacts do
  @moduledoc """
  Discovers Chronicle artifacts in an OTP application.

  Discovery is based on the introspection functions generated by Chronicle
  macros:

    * `__chronicle_event_type__/1`
    * `__chronicle_reactor__/1`
    * `__chronicle_reducer__/1`
    * `__chronicle_read_model__/1`
    * `__chronicle_webhook__/1`
    * `__chronicle_event_store_subscription__/1`
    * `__chronicle_migration__/1`

  The returned map can be fed directly into `Chronicle.Client` options.
  """

  @type discovered :: %{
          event_types: [module()],
          reactors: [module()],
          reducers: [module()],
          read_models: [module()],
          projections: [module()],
          seeders: [module()],
          webhooks: [module()],
          event_store_subscriptions: [module()],
          migrations: [module()]
        }

  @doc """
  Discovers Chronicle artifacts from modules belonging to an OTP app.

  Returns empty lists if the app has no module list available.
  """
  @spec discover(atom()) :: discovered()
  def discover(otp_app) when is_atom(otp_app) do
    modules =
      case :application.get_key(otp_app, :modules) do
        {:ok, app_modules} when is_list(app_modules) -> app_modules
        _ -> []
      end

    Enum.reduce(
      modules,
      %{
        event_types: [],
        reactors: [],
        reducers: [],
        read_models: [],
        projections: [],
        seeders: [],
        webhooks: [],
        event_store_subscriptions: [],
        migrations: []
      },
      fn module, acc ->
        if Code.ensure_loaded?(module) do
          acc
          |> maybe_put(
            :event_types,
            module,
            function_exported?(module, :__chronicle_event_type__, 1)
          )
          |> maybe_put(:reactors, module, function_exported?(module, :__chronicle_reactor__, 1))
          |> maybe_put(:reducers, module, function_exported?(module, :__chronicle_reducer__, 1))
          |> maybe_put(
            :read_models,
            module,
            function_exported?(module, :__chronicle_read_model__, 1)
          )
          |> maybe_put(
            :projections,
            module,
            function_exported?(module, :__chronicle_projection__, 1)
          )
          |> maybe_put(:seeders, module, function_exported?(module, :__chronicle_seeder__, 1))
          |> maybe_put(:webhooks, module, function_exported?(module, :__chronicle_webhook__, 1))
          |> maybe_put(
            :event_store_subscriptions,
            module,
            function_exported?(module, :__chronicle_event_store_subscription__, 1)
          )
          |> maybe_put(
            :migrations,
            module,
            function_exported?(module, :__chronicle_migration__, 1)
          )
        else
          acc
        end
      end
    )
    |> Enum.map(fn {key, value} -> {key, Enum.reverse(value)} end)
    |> Map.new()
  end

  @doc """
  Discovers Chronicle artifacts from all currently loaded modules.

  Useful as a zero-configuration default in early adoption scenarios.
  """
  @spec discover_loaded() :: discovered()
  def discover_loaded do
    modules =
      :code.all_loaded()
      |> Enum.map(fn {module, _} -> module end)

    Enum.reduce(
      modules,
      %{
        event_types: [],
        reactors: [],
        reducers: [],
        read_models: [],
        projections: [],
        seeders: [],
        webhooks: [],
        event_store_subscriptions: [],
        migrations: []
      },
      fn module, acc ->
        acc
        |> maybe_put(
          :event_types,
          module,
          function_exported?(module, :__chronicle_event_type__, 1)
        )
        |> maybe_put(:reactors, module, function_exported?(module, :__chronicle_reactor__, 1))
        |> maybe_put(:reducers, module, function_exported?(module, :__chronicle_reducer__, 1))
        |> maybe_put(
          :read_models,
          module,
          function_exported?(module, :__chronicle_read_model__, 1)
        )
        |> maybe_put(
          :projections,
          module,
          function_exported?(module, :__chronicle_projection__, 1)
        )
        |> maybe_put(:seeders, module, function_exported?(module, :__chronicle_seeder__, 1))
        |> maybe_put(:webhooks, module, function_exported?(module, :__chronicle_webhook__, 1))
        |> maybe_put(
          :event_store_subscriptions,
          module,
          function_exported?(module, :__chronicle_event_store_subscription__, 1)
        )
        |> maybe_put(
          :migrations,
          module,
          function_exported?(module, :__chronicle_migration__, 1)
        )
      end
    )
    |> Enum.map(fn {key, value} -> {key, Enum.reverse(value)} end)
    |> Map.new()
  end

  defp maybe_put(acc, _key, _module, false), do: acc
  defp maybe_put(acc, key, module, true), do: Map.update!(acc, key, &[module | &1])
end
