# Copyright (c) Cratis. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

defmodule Chronicle.Client do
  @moduledoc """
  Supervisor that manages a Chronicle connection and all registered observers.

  `Chronicle.Client` is the main entry point for the Chronicle Elixir client.
  Start it in your application's supervision tree, providing a connection
  string and the list of event types, migrations, reactors, reducers, read
  models, discoverable webhooks, and discoverable event store subscriptions to
  register.

  ## Usage

  In your `Application.start/2`:

      def start(_type, _args) do
        children = [
          {Chronicle.Client,
            connection_string: "chronicle://localhost:35000",
            event_store: "my-store",
            event_types: [
              MyApp.Events.AccountOpened,
              MyApp.Events.FundsDeposited
            ],
            migrations: [MyApp.Migrations.AccountOpenedV2Migration],
            reactors: [MyApp.Reactors.NotificationReactor],
            reducers: [MyApp.Reducers.AccountReducer],
            read_models: [MyApp.ReadModels.Account],
            webhooks: [MyApp.WebHooks.AccountEvents],
            event_store_subscriptions: [
              MyApp.EventStoreSubscriptions.DefaultAccountEvents
            ]}
        ]

        Supervisor.start_link(children, strategy: :one_for_one)
      end

  Or enable artifact auto-discovery from an OTP application:

      {Chronicle.Client,
        connection_string: "chronicle://localhost:35000",
        event_store: "my-store",
        otp_app: :my_app}

  In that mode, Chronicle scans modules in `:my_app` and discovers artifacts
  generated by Chronicle macros (`use Chronicle.Events.EventType`,
  `use Chronicle.Events.Migration`, `use Chronicle.Seeding.Seeder`,
  `use Chronicle.Reactors.Reactor`, `use Chronicle.Reducers.Reducer`, `use Chronicle.ReadModels.ReadModel`,
  `use Chronicle.WebHooks.Webhook`, and
  `use Chronicle.EventStoreSubscriptions.Subscription`).

  By default, Chronicle also auto-discovers artifacts from loaded modules,
  so consumers can start with minimal configuration.

  Read models that contain `from/2`, `join/2`, or `removed_with/2` declarations
  are automatically registered as server-side projections.

  ## Multiple clients

  You can start multiple clients with different names:

      {Chronicle.Client,
        name: :bank_chronicle,
        connection_string: "chronicle://bank-server:35000",
        event_store: "bank"}

      {Chronicle.Client,
        name: :crm_chronicle,
        connection_string: "chronicle://crm-server:35000",
        event_store: "crm"}

  ## Options

    * `:name` — registered name for this client. Defaults to `Chronicle.Client`.
    * `:connection_string` — a connection string binary or
      `Chronicle.Connections.ConnectionString` struct. Defaults to
      `ConnectionString.default/0` (localhost:35000).
    * `:event_store` — the event store name. Defaults to `"default"`.
    * `:namespace` — the namespace within the event store. Defaults to `"default"`.
    * `:discover` — enable/disable artifact auto-discovery. Defaults to `true`.
    * `:otp_app` — optional OTP application to auto-discover Chronicle artifacts from.
      When omitted, discovery scans loaded modules. Discovered artifacts are
      merged with explicit `:event_types`, `:migrations`, `:reactors`,
      `:reducers`, `:read_models`, `:webhooks`, and
      `:event_store_subscriptions` entries.
    * `:event_types` — list of event type modules to register with the event store.
    * `:migrations` — list of migration modules to register with the event store.
    * `:reactors` — list of reactor modules to start (each `use Chronicle.Reactors.Reactor`).
    * `:reducers` — list of reducer modules to start (each `use Chronicle.Reducers.Reducer`).
    * `:read_models` — list of read model modules (each `use Chronicle.ReadModels.ReadModel`).
      Modules that contain `from/2` declarations are registered as model-bound projections.
    * `:projections` — list of declarative projection modules (each
      `use Chronicle.Projections.Projection`). These are standalone projection definitions
      that reference a separate read model module.
    * `:seeders` — list of seeder modules (each `use Chronicle.Seeding.Seeder`). Seeders
      populate the event store with initial events during client startup.
    * `:webhooks` — list of discoverable webhook modules (each
      `use Chronicle.WebHooks.Webhook`). These are registered on startup.
    * `:event_store_subscriptions` — list of discoverable event store
      subscription modules (each
      `use Chronicle.EventStoreSubscriptions.Subscription`). These are
      registered on startup.
    * `:default_sink_type_id` — the default sink type used when registering
      projections and reducers. Accepts an atom (`:mongodb`, `:sql`,
      `:in_memory`, `:none`) or a raw sink type string. Defaults to
      `:mongodb`. See `Chronicle.Sinks.WellKnownSinkTypes`.
    * `:skip_tls_validation` — overrides the connection string's
      `skipTlsValidation` query option. See `Chronicle.Connections.Connection`.
    * `:load_balancer` — overrides the connection string's `loadBalancer`
      query option (`:least_connections`, `:round_robin`, or `:random`), used
      to pick among multiple hosts or DNS SRV-resolved addresses. See
      `Chronicle.Connections.LoadBalancer`.

  ## Convenience functions

  Once started, use `Chronicle.append/3` and `Chronicle.read_model/3` for the
  most common operations, or use the subsystem modules directly:

    * `Chronicle.EventSequences.EventLog` — append and query events
    * `Chronicle.ReadModels` — query read model instances
    * `Chronicle.Events.EventTypes` — manage event type registrations
    * `Chronicle.Jobs` — inspect and control Chronicle jobs
    * `Chronicle.WebHooks` — inspect and register webhooks
    * `Chronicle.EventStoreSubscriptions` — register cross-store subscriptions
  """

  use Supervisor

  alias Chronicle.Artifacts
  alias Chronicle.Connections.Connection
  alias Chronicle.Sinks.WellKnownSinkTypes

  @doc """
  Starts a Chronicle client supervisor linked to the current process.
  """
  @spec start_link(keyword()) :: Supervisor.on_start()
  def start_link(opts \\ []) do
    name = Keyword.get(opts, :name, __MODULE__)
    Supervisor.start_link(__MODULE__, opts, name: name)
  end

  @doc """
  Returns the stored configuration for the given client name.

  Used internally by `Chronicle.EventSequences.EventLog`, `Chronicle.ReadModels`, etc.
  """
  @spec config(atom() | pid()) :: map()
  def config(client \\ __MODULE__) do
    :persistent_term.get({__MODULE__, client})
  end

  @impl true
  def init(opts) do
    name = Keyword.get(opts, :name, __MODULE__)
    conn_name = connection_name(name)

    event_store = Keyword.get(opts, :event_store, "default")
    namespace = Keyword.get(opts, :namespace, "Default")
    discover? = Keyword.get(opts, :discover, true)

    default_sink_type_id =
      opts |> Keyword.get(:default_sink_type_id, :mongodb) |> WellKnownSinkTypes.resolve()

    discovered =
      if discover? do
        case Keyword.get(opts, :otp_app) do
          nil -> Artifacts.discover_loaded()
          otp_app -> Artifacts.discover(otp_app)
        end
      else
        %{
          event_types: [],
          migrations: [],
          reactors: [],
          reducers: [],
          read_models: [],
          projections: [],
          seeders: [],
          webhooks: [],
          event_store_subscriptions: []
        }
      end

    event_types = Enum.uniq(Keyword.get(opts, :event_types, []) ++ discovered.event_types)
    migrations = Enum.uniq(Keyword.get(opts, :migrations, []) ++ discovered.migrations)
    reactors = Enum.uniq(Keyword.get(opts, :reactors, []) ++ discovered.reactors)
    reducers = Enum.uniq(Keyword.get(opts, :reducers, []) ++ discovered.reducers)
    read_models = Enum.uniq(Keyword.get(opts, :read_models, []) ++ discovered.read_models)
    projections = Enum.uniq(Keyword.get(opts, :projections, []) ++ discovered.projections)
    seeders = Enum.uniq(Keyword.get(opts, :seeders, []) ++ discovered.seeders)
    webhooks = Enum.uniq(Keyword.get(opts, :webhooks, []) ++ discovered.webhooks)

    event_store_subscriptions =
      Enum.uniq(
        Keyword.get(opts, :event_store_subscriptions, []) ++
          discovered.event_store_subscriptions
      )

    lifecycle_name = Chronicle.Connections.Lifecycle.name_for(name)

    :persistent_term.put({__MODULE__, name}, %{
      connection: conn_name,
      lifecycle: lifecycle_name,
      event_store: event_store,
      namespace: namespace,
      event_types: event_types,
      reducers: reducers,
      seeders: seeders,
      webhooks: webhooks,
      event_store_subscriptions: event_store_subscriptions
    })

    connection_opts =
      opts
      |> Keyword.take([
        :connection_string,
        :server_address,
        :skip_tls_validation,
        :load_balancer,
        :grpc_options,
        :retry_attempts,
        :reconnect_base_delay,
        :reconnect_max_delay
      ])
      |> Keyword.put(:name, conn_name)

    observer_opts = [
      client: name,
      connection: conn_name,
      lifecycle: lifecycle_name,
      event_store: event_store,
      namespace: namespace,
      default_sink_type_id: default_sink_type_id
    ]

    reactor_children =
      Enum.map(reactors, fn module ->
        Supervisor.child_spec(
          {Chronicle.Reactors.Handler, Keyword.put(observer_opts, :module, module)},
          id: {Chronicle.Reactors.Handler, module}
        )
      end)

    reducer_children =
      Enum.map(reducers, fn module ->
        Supervisor.child_spec(
          {Chronicle.Reducers.Handler, Keyword.put(observer_opts, :module, module)},
          id: {Chronicle.Reducers.Handler, module}
        )
      end)

    webhook_children =
      if Enum.empty?(webhooks) do
        []
      else
        [{Chronicle.WebHooks.Registrar, client: name, lifecycle: lifecycle_name}]
      end

    event_store_subscription_children =
      if Enum.empty?(event_store_subscriptions) do
        []
      else
        [{Chronicle.EventStoreSubscriptions.Registrar, client: name, lifecycle: lifecycle_name}]
      end

    seeder_children =
      if Enum.empty?(seeders) do
        []
      else
        [
          {Chronicle.Seeding.Runner,
           client: name,
           connection: conn_name,
           lifecycle: lifecycle_name,
           event_store: event_store,
           namespace: namespace,
           seeders: seeders}
        ]
      end

    children =
      [
        GRPC.Client.Supervisor,
        {Chronicle.Connections.Lifecycle, client: name},
        {Connection, connection_opts},
        {Chronicle.Connections.Session,
         connection: conn_name, client_name: name, lifecycle: lifecycle_name},
        {Chronicle.Registration.Coordinator,
         Keyword.merge(observer_opts,
           event_types: event_types,
           migrations: migrations,
           read_models: read_models,
           reducers: reducers,
           projections: projections
         )}
      ] ++
        reactor_children ++
        reducer_children ++
        seeder_children ++
        webhook_children ++
        event_store_subscription_children

    # rest_for_one: the lifecycle hub is the root dependency — if it restarts,
    # everything that subscribes to it restarts and re-subscribes, picking up the
    # current phase via the snapshot returned on subscribe.
    Supervisor.init(children, strategy: :rest_for_one)
  end

  @doc false
  def connection_name(client_name), do: :"#{client_name}.Connection"
end
