#!/usr/bin/env python3
# Copyright (c) Cratis. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

import re
import subprocess
import sys
import textwrap
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
MIX_ROOT = REPO_ROOT / "Source" / "chronicle"
SNIPPET_ROOT = REPO_ROOT / "Documentation" / "client-snippets"
GENERATED_TEST = MIX_ROOT / "test" / "chronicle" / "docs_snippets_compilation_test.exs"
FENCE_RE = re.compile(r"```([^\s`]+)[^\n]*\n(.*?)\n```", re.DOTALL)
UNSUPPORTED_SNIPPET_MARKER = "does not support this workflow yet"

BODY_SNIPPETS = {
    "get-started/client-flow": [
        "",
        "",
    ],
    "events/appending/schema-validation": [
        """
        event_source_id = "order-123"
        customer_id = "customer-42"
        total = 42
        """,
    ],
    "events/appending/occurred": [
        """
        event_source_id = "order-123"
        customer_id = "customer-42"
        total = 42
        """,
    ],
    "read-models/getting-single-instance/basic": [
        """
        account_id = "account-42"
        """,
    ],
    "read-models/getting-collection-instances/basic": [
        "",
    ],
    "read-models/getting-collection-instances/filtering": [
        """
        threshold = 1_000
        """,
    ],
    "read-models/getting-collection-instances/event-count": [
        "",
    ],
    "read-models/getting-snapshots/basic": [
        """
        order_id = "order-123"
        """,
    ],
    "read-models/getting-snapshots/analyze": [
        """
        order_id = "order-123"
        """,
    ],
}

COMMON_MODULES = [
    """
    defmodule MyApp.ReadModels.AccountInfo do
      use Chronicle.ReadModels.ReadModel

      defstruct name: nil, balance: 0
    end
    """,
    """
    defmodule MyApp.ReadModels.Account do
      use Chronicle.ReadModels.ReadModel

      defstruct id: nil, name: nil, balance: 0, created_date: nil
    end
    """,
    """
    defmodule MyApp.ReadModels.Order do
      use Chronicle.ReadModels.ReadModel

      defstruct id: nil, status: :new, total_amount: 0
    end
    """,
]


def snippet_files() -> list[Path]:
    files = sorted([*SNIPPET_ROOT.rglob("*.md"), *SNIPPET_ROOT.rglob("*.mdx")])
    snippets = {}
    for path in files:
        key = snippet_key(path)
        if key in snippets:
            raise ValueError(f"Duplicate client snippet {key}: {snippets[key]} and {path.relative_to(REPO_ROOT)}")
        snippets[key] = path.relative_to(REPO_ROOT)
    return files


def snippet_key(path: Path) -> str:
    return path.relative_to(SNIPPET_ROOT).with_suffix("").as_posix()


def extract_snippets(path: Path) -> list[str]:
    raw = path.read_text(encoding="utf-8")
    matches = FENCE_RE.findall(raw)
    if not matches:
        raise ValueError(f"{path.relative_to(REPO_ROOT)} must contain at least one fenced Elixir snippet")

    snippets = []
    for language, code in matches:
        if language == "text" and UNSUPPORTED_SNIPPET_MARKER in code:
            continue
        if language != "elixir":
            raise ValueError(f"{path.relative_to(REPO_ROOT)} must use elixir code fences, got {language!r}")
        snippets.append(code.strip())
    return snippets


def function_name(relative_path: str, index: int) -> str:
    name = "snippet_" + re.sub(r"[^A-Za-z0-9_]", "_", relative_path)
    return f"{name}_{index + 1}"


def body_function(relative_path: str, index: int, prelude: str, code: str) -> str:
    lines = [line for line in [textwrap.dedent(prelude).strip(), code] if line]
    body = textwrap.indent("\n\n".join(lines), "    ")
    return f"  def {function_name(relative_path, index)} do\n{body}\n  end"


def generate_test() -> str:
    files = snippet_files()
    if not files:
        raise ValueError(f"No client snippets found in {SNIPPET_ROOT}")

    modules: list[str] = [textwrap.dedent(module).strip() for module in COMMON_MODULES]
    functions: list[str] = []

    for path in files:
        relative_path = snippet_key(path)
        snippets = extract_snippets(path)

        if relative_path in BODY_SNIPPETS:
            preludes = BODY_SNIPPETS[relative_path]
            if len(preludes) != len(snippets):
                raise ValueError(f"{relative_path} has {len(snippets)} snippets but {len(preludes)} compile preludes")
            for index, snippet in enumerate(snippets):
                functions.append(body_function(relative_path, index, preludes[index], snippet))
        else:
            modules.extend(snippets)

    function_block = "\n\n".join(functions)

    return "\n\n".join([
        "# This file is generated by Documentation/validate-client-snippets.py.",
        *modules,
        f"defmodule MyApp.DocsSnippetBodies do\n{function_block}\nend",
        "defmodule Chronicle.DocsSnippetsCompilationTest do\n  use ExUnit.Case, async: true\n\n  test \"documentation snippets compile\" do\n    assert true\n  end\nend",
        "",
    ])


def main() -> int:
    GENERATED_TEST.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_TEST.write_text(generate_test(), encoding="utf-8")

    try:
        subprocess.run(
            ["mix", "test", "test/chronicle/docs_snippets_compilation_test.exs", "--warnings-as-errors"],
            cwd=MIX_ROOT,
            check=True,
        )
    finally:
        GENERATED_TEST.unlink(missing_ok=True)

    print("Elixir Chronicle client snippets compiled successfully.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"Client snippet validation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
